#!/bin/bash
FILE=$1;
while read line; do
   echo " <input type=\"checkbox\" id=\"$line\" class=\"hide\"/>

              <label for=\"$line\" class=\"input-type-link\">
              НАЗВАНИЕ МОДУЛЯ
              </label> 

              <div> 
              <form onInput=\"${line}_handle()\">
              <input id=\"${line}_n1\" class=\"input-field\" type=\"text\" 
                     placeholder=\"Первое число\"/>
              <input id=\"${line}_n2\" class=\"input-field\" type=\"text\" 
                     placeholder=\"Второе число\"/>
              </form>
              Ответ: 
              <span id=\"${line}_result\" class=\"result\"></span>

              <script type=\"text/javascript\">
function ${line}_handle() {
  var number1 = MathLib.parsePolynom(document.getElementById(
        \"${line}_n1\").value);
  var number2 = MathLib.parsePolynom(document.getElementById(
        \"${line}_n2\").value);
  var result = MathLib.$line(number1, number2);
  document.getElementById(\"${line}_result\").innerHTML = 
    MathLib.polynomToString(result);
}
      </script>

              </div>"
done < $FILE
